package SumApp;


/**
* SumApp/Sum.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sum.idl
* lunes 17 de junio de 2019 16H50' COT
*/

public interface Sum extends SumOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Sum
