package SumApp;

/**
* SumApp/SumHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sum.idl
* lunes 17 de junio de 2019 16H50' COT
*/

public final class SumHolder implements org.omg.CORBA.portable.Streamable
{
  public SumApp.Sum value = null;

  public SumHolder ()
  {
  }

  public SumHolder (SumApp.Sum initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = SumApp.SumHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    SumApp.SumHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return SumApp.SumHelper.type ();
  }

}
