package SumApp;


/**
* SumApp/SumHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sum.idl
* lunes 17 de junio de 2019 16H50' COT
*/

abstract public class SumHelper
{
  private static String  _id = "IDL:SumApp/Sum:1.0";

  public static void insert (org.omg.CORBA.Any a, SumApp.Sum that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static SumApp.Sum extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (SumApp.SumHelper.id (), "Sum");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static SumApp.Sum read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_SumStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, SumApp.Sum value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static SumApp.Sum narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof SumApp.Sum)
      return (SumApp.Sum)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      SumApp._SumStub stub = new SumApp._SumStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static SumApp.Sum unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof SumApp.Sum)
      return (SumApp.Sum)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      SumApp._SumStub stub = new SumApp._SumStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
