package SumApp;


/**
* SumApp/SumOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sum.idl
* lunes 17 de junio de 2019 16H50' COT
*/

public interface SumOperations 
{
  double sum (double n1, double n2);
  double res (double n1, double n2);
  double mult (double n1, double n2);
  double division (double n1, double n2);
  void shutdown ();
} // interface SumOperations
