package SumApp;


/**
* SumApp/SumPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sum.idl
* lunes 17 de junio de 2019 16H50' COT
*/

public abstract class SumPOA extends org.omg.PortableServer.Servant
 implements SumApp.SumOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sum", new java.lang.Integer (0));
    _methods.put ("res", new java.lang.Integer (1));
    _methods.put ("mult", new java.lang.Integer (2));
    _methods.put ("division", new java.lang.Integer (3));
    _methods.put ("shutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // SumApp/Sum/sum
       {
         double n1 = in.read_double ();
         double n2 = in.read_double ();
         double $result = (double)0;
         $result = this.sum (n1, n2);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 1:  // SumApp/Sum/res
       {
         double n1 = in.read_double ();
         double n2 = in.read_double ();
         double $result = (double)0;
         $result = this.res (n1, n2);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 2:  // SumApp/Sum/mult
       {
         double n1 = in.read_double ();
         double n2 = in.read_double ();
         double $result = (double)0;
         $result = this.mult (n1, n2);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 3:  // SumApp/Sum/division
       {
         double n1 = in.read_double ();
         double n2 = in.read_double ();
         double $result = (double)0;
         $result = this.division (n1, n2);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 4:  // SumApp/Sum/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:SumApp/Sum:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Sum _this() 
  {
    return SumHelper.narrow(
    super._this_object());
  }

  public Sum _this(org.omg.CORBA.ORB orb) 
  {
    return SumHelper.narrow(
    super._this_object(orb));
  }


} // class SumPOA
